from util.config import generate_config

configs = {
    'cub200_contrastive': generate_config({
        'image': {},
        'dataset': {'name': 'cub200'},
        'batch_design': {'name': 'grouped', 'group_size': 4, 'batch_size': 64, 'num_batches': 100},
        'model': {'name': 'resnet50', 'dimension': 128},
        'loss': {'name': 'l1_contrastive', 'alpha': 4.0, 'new_importance_sampling': True, 'l': 512},
        'metrics': {'recall': True, 'recall_k': [1, 2]},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.00003, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
    'lfw_contrastive': generate_config({
        'image': {},
        'dataset': {'name': 'lfw'},
        'batch_design': {'name': 'grouped', 'group_size': 4, 'batch_size': 64, 'num_batches': 100},
        'model': {'name': 'resnet50', 'dimension': 128},
        'loss': {'name': 'l1_contrastive', 'alpha': 8.0, 'new_importance_sampling': True, 'l': 512},
        'metrics': {'recall': True, 'recall_k': [1, 2], 'lfw_acc': True},
        'trainer': {'lr_decay_steps': 1000, 'learning_rate': 0.00003, 'num_epochs': 200, 'lr_decay_rate': 0.9},
    }),
    'lfw_npair': generate_config({
        'image': {},
        'dataset': {'name': 'lfw'},
        'batch_design': {'name': 'grouped', 'group_size': 2, 'batch_size': 64, 'npair': 32},
        'model': {'name': 'resnet50', 'dimension': 128},
        'loss': {'name': 'npair', 'lambda': 0.001},
        'metrics': {'recall': True, 'recall_k': [1, 2]},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.00003, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
    'cars196_npair': generate_config({
        'image': {},
        'dataset': {'name': 'cars196'},
        'batch_design': {'name': 'grouped', 'group_size': 2, 'batch_size': 64, 'npair': 32},
        'model': {'name': 'resnet50', 'dimension': 128},
        'loss': {'name': 'npair', 'lambda': 0.001},
        'metrics': {'auc': True, 'recall': True, 'nmi': True, 'vrf': True},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.0001, 'lr_embedding': 0.0001, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
    'cub200_npair': generate_config({
        'image': {},
        'dataset': {'name': 'cub200'},
        'batch_design': {'name': 'grouped', 'group_size': 2, 'batch_size': 64, 'npair': 32, 'negative_class_mining': True},
        'model': {'name': 'resnet50', 'dimension': 128},
        'loss': {'name': 'npair', 'lambda': 0.001, 'importance_sampling': True},
        'metrics': {'auc': True, 'recall': True, 'nmi': True},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.0001, 'lr_embedding': 0.0001, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
    'cub200_margin': generate_config({
        'image': {},
        'dataset': {'name': 'cub200'},
        'batch_design': {'name': 'grouped', 'group_size': 4, 'batch_size': 64},
        'model': {'name': 'resnet50', 'dimension': 128, 'l2_normalize': True},
        'loss': {'name': 'margin'},
        'metrics': {'auc': True, 'recall': True, 'nmi': True},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.0001, 'lr_embedding': 0.0001, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
    'cub200_triplet': generate_config({
        'image': {},
        'dataset': {'name': 'cub200'},
        'batch_design': {'name': 'grouped', 'group_size': 4, 'batch_size': 64},
        'model': {'name': 'resnet50', 'dimension': 128, 'l2_normalize': True},
        'loss': {'name': 'triplet', 'alpha': 1.0},
        'metrics': {'auc': True, 'recall': True, 'nmi': True},
        'trainer': {'lr_decay_steps': 100, 'learning_rate': 0.00003, 'num_epochs': 20, 'lr_decay_rate': 0.9},
    }),
}
